<?php

namespace MarketingBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function computeDQL($date){
        $qb=$this->getEntityManager()
            ->createQuery("DELETE FROM MarketingBundle:Promotion p  WHERE p.dateFin < :date")
           ->setParameter('date',$date);
        return $qb->getResult();
    }

}
