<?php

namespace CommunicationBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function CommentsCount ( $id){

        return $this->getEntityManager()
            ->createQuery(

                "SELECT COUNT(p.id) AS c FROM CommunicationBundle:Comment p WHERE p.post IN 
                    (SELECT x FROM CommunicationBundle:BlogPost x where x.id='$id') "
            )
            ->getResult();

    }
}
