<?php

namespace ServicesBundle\Repository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($id)
    {
        $dqlresult=$this->getEntityManager()
            ->createQuery("select m from ServicesBundle:Wishlist m where m.User = '$id'");
        return $dqlresult->getResult();
    }
    public function findByCategorie($categorie,$id)
    {
        $dqlresult=$this->getEntityManager()
            ->createQuery("select m from ProduitBundle:Produit m where m.Categorie = $categorie
                    and     m.id NOT IN (SELECT x.id FROM ProduitBundle:Produit x,ServicesBundle:Wishlist y WHERE y.User = '$id' AND x.id = y.Produit)");

        //->createQuery("select m from ProduitBundle:Produit m where m.categorie = '$categorie' and m.id NOT IN (SELECT x.Produit FROM ServicesBundle:Wishlist x WHERE x.User = '$id'  )");
        return $dqlresult->getResult();
        //SELECT * FROM `produit` WHERE categorie = 1 AND id NOT IN (select p.produit_id from wishlist p WHERE p.user_id = 1 )
    }

    public function WishlistSearchajax($valeur,$id)
    {
        $dqlresult=$this->getEntityManager()
            ->createQuery("select m from ProduitBundle:Produit m where   m.nom LIKE '$valeur%' 
        AND m.Categorie IN  (SELECT cccc FROM ProduitBundle:Categorie cccc,ProduitBundle:Produit pppp,ServicesBundle:Wishlist wwww where  cccc.id = pppp.Categorie AND pppp.id = wwww.Produit)
     
        AND m.id NOT IN (SELECT x.id FROM ProduitBundle:Produit x,ServicesBundle:Wishlist y WHERE y.User = '$id' AND x.id = y.Produit)");

        return $dqlresult->getResult();
    }


}