<?php

namespace ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDQL($key)
    {
        $query = $this->getEntityManager()
            ->createQuery("
	            SELECT p FROM ProduitBundle:produit p
	            WHERE p.nom LIKE '%?1%' "
            )->setParameter(1, $key);
        return $query->getResult();
    }
    public function findByUser($id)
    {
        $dqlresult=$this->getEntityManager()
            ->createQuery("select m from ServicesBundle:Wishlist m where m.User = '$id'");
        return $dqlresult->getResult();
    }


    public function sortByPrixASC()
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from ProduitBundle:produit m ORDER BY m.prix ASC");
        return $query->getResult();
    }

    public function sortByPrixDES()
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from ProduitBundle:produit m ORDER BY m.prix DESC ");
        return $query->getResult();
    }

    public function Rechdate($date)
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from ProduitBundle:produit m WHERE :date - m.updatedAt  ")->setParameter('date' , $date);
        return $query->getResult();
    }
    public function search($search)
    {
        $query = $this->getEntityManager()->createQueryBuilder('p')
            ->select('p ')->from('ProduitBundle\Entity\Produit','p')->where('p.nom like :nom ')
            ->setParameter('nom',$search. '%')

            ->getQuery();
        $adoptions= $query->getResult();
        return $adoptions;
    }


    public function SearchByName($nom)
    {
        return $this->getEntityManager()->createQuery("SELECT m from ProduitBundle:produit m WHERE m.nom LIKE '$nom%'")
            ->getResult();
    }


}
