<?php

namespace VenteBundle\Repository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPanierByUser($id){
        return $this->getEntityManager()->createQuery("SELECT i FROM  VenteBundle:Panier i WHERE i.user IN 
                (SELECT u FROM PepiniereBundle:User  u WHERE u.id = '$id')")
        ->getResult();

    }

    public function getByproduit($id){
        return $this->getEntityManager()->createQuery("SELECT i FROM  ProduitBundle:Produit i WHERE i.id= '$id'")
          ->getResult();
    }

    public function finndDdepartByLivraison($id){
        return $this->getEntityManager()->createQuery("SELECT i FROM  VenteBundle:Livraison i WHERE i.id= '$id'")
            ->getResult();
    }

}
